install_data('dev.miguel.Lucent.desktop',
  install_dir: get_option('datadir') / 'applications',
)

install_data('dev.miguel.Lucent.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)

install_data('icons/hicolor/scalable/apps/dev.miguel.Lucent.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)
